---
abstract: 'Query class on Wikibase item.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.59
  Test::MockObject: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Shared::Fixture::Wikibase::Datatype::Item::Wikidata::Dog: 0.24
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wikibase-Datatype-Query
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.03
  Error::Pure: 0.15
  Scalar::Util: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Wikibase-Datatype-Query/issues
  homepage: https://github.com/michal-josef-spacek/Wikibase-Datatype-Query
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Wikibase-Datatype-Query
version: '0.01'
